#!/bin/sh
set -e -x
git --version
upstream=$1
: ${upstream:=transforlab}
: ${REPO:=git@github.com:transforlab/hackfoldr-2.0}
git fetch $upstream
if [ `git rev-list HEAD...$upstream/master --count` -ne 0 ]; then
  echo "not deploying"
  exit 1
fi
npm i
rm -rf _public
# XXX: use --reference when not in shallow clone
#git clone $REPO --reference . -b gh-pages _public
git clone $REPO -b gh-pages _public
rm -rf _public/*
REV=`git describe --always`
BUILD=git-$REV ./node_modules/.bin/gulp build
cd _public
git remote add deploy dokku@apps.ecobytes.net:hackfoldr
git add -A .
echo "regen for $REV" | git commit-tree `git write-tree` -p `git rev-parse HEAD` -p $REV | xargs git reset --hard
git push -f deploy gh-pages:master
cd ..
